package com.lenicliu.spring.boot.mapper;

import com.lenicliu.spring.boot.model.Message;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from MESSAGE",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into MESSAGE (ID, AUTHOR, ",
        "EMAIL, CONTENT, ",
        "CREATED)",
        "values (#{id,jdbcType=INTEGER}, #{author,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{created,jdbcType=TIMESTAMP})"
    })
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, AUTHOR, EMAIL, CONTENT, CREATED",
        "from MESSAGE",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="AUTHOR", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENT", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED", property="created", jdbcType=JdbcType.TIMESTAMP)
    })
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, AUTHOR, EMAIL, CONTENT, CREATED",
        "from MESSAGE"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="AUTHOR", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENT", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED", property="created", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Message> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated
     */
    @Update({
        "update MESSAGE",
        "set AUTHOR = #{author,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "CONTENT = #{content,jdbcType=VARCHAR},",
          "CREATED = #{created,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Message record);
}