DROP TABLE IF EXISTS OPTION;
CREATE TABLE OPTION (
	NAME VARCHAR(100) PRIMARY KEY NOT NULL,
	VALUE VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS NOTE;
CREATE TABLE NOTE (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    LINK VARCHAR(100) UNIQUE NOT NULL,
    STATUS INT NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    CREATED BIGINT NOT NULL,
    UPDATED BIGINT NOT NULL
);